### PR TITLE
feat!: remove locale files in favor of atlas - FC-0012 - OEP-58

### PR DESCRIPTION
**Pull request by shadinaif**
Breaking change!
---

This PR is related to https://github.com/openedx/xblock-image-explorer/pull/112. But it is meant to be merged in a later phase. 

Here we 100% comply with [FC-0012](https://openedx.atlassian.net/l/cp/XGS0iCcQ) by not having any translation files living inside Open-edX repositories

Changes
---

- [x] Remove source and language translations from the repositories, hence no `.po` or `.mo` files will be committed into the repos. 
- [ ] ~~Remove failing tests that require the presence of translation files~~ not available

Merge timeline
---

**## Keep this pull request as a draft to prevent an accidental merge. ##**

Pre-merge checklist
---

- [ ] [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) has been closed, published, and used by the community for a while
- [ ] @brian-smith-tcril approves the merge

References
---

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shadinaif! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by shadinaif** [comment]
please review @OmarIthawi

**Review by OmarIthawi — APPROVED** [review]

**Comment by OmarIthawi** [comment]
@shadinaif please set as `ready for merge` by removing `draft` status.

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@shadinaif 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-image-explorer&entry.867055334=https://github.com/openedx/xblock-image-explorer/pull/114&entry.1484655318=https://github.com/shadinaif&entry.752974735=2024-02-09+07:50&entry.1917517419=2024-03-18+18:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
